import type { Doctor } from './types';

export const DOCTORS: Doctor[] = [
  {
    id: 1,
    name: 'Dr. Evelyn Reed',
    specialty: 'Umutima (Cardiologist)',
    rating: 4.9,
    reviews: 182,
    imageUrl: 'https://picsum.photos/seed/doc1/200/200',
    consultationFee: 150000,
  },
  {
    id: 2,
    name: 'Dr. Samuel Chen',
    specialty: 'Ubuvuzi Rusange',
    rating: 4.8,
    reviews: 250,
    imageUrl: 'https://picsum.photos/seed/doc2/200/200',
    consultationFee: 80000,
  },
  {
    id: 3,
    name: 'Dr. Isabella Monroe',
    specialty: 'Uruhu (Dermatologist)',
    rating: 4.9,
    reviews: 215,
    imageUrl: 'https://picsum.photos/seed/doc3/200/200',
    consultationFee: 120000,
  },
  {
    id: 4,
    name: 'Dr. Julian Baker',
    specialty: 'Abana (Pediatrician)',
    rating: 5.0,
    reviews: 310,
    imageUrl: 'https://picsum.photos/seed/doc4/200/200',
    consultationFee: 100000,
  },
  {
    id: 5,
    name: 'Dr. Anita Sharma',
    specialty: 'Amenyo (Dentist)',
    rating: 4.9,
    reviews: 280,
    imageUrl: 'https://picsum.photos/seed/doc5/200/200',
    consultationFee: 95000,
  },
  {
    id: 6,
    name: 'Dr. Ben Carter',
    specialty: 'Indwara zo mu mutwe (Psychiatrist)',
    rating: 4.8,
    reviews: 195,
    imageUrl: 'https://picsum.photos/seed/doc6/200/200',
    consultationFee: 160000,
  },
  {
    id: 7,
    name: 'Dr. Olivia Garcia',
    specialty: 'Amagufa (Orthopedist)',
    rating: 4.9,
    reviews: 230,
    imageUrl: 'https://picsum.photos/seed/doc7/200/200',
    consultationFee: 135000,
  },
  {
    id: 8,
    name: 'Dr. Liam Wong',
    specialty: 'Amaso (Ophthalmologist)',
    rating: 5.0,
    reviews: 290,
    imageUrl: 'https://picsum.photos/seed/doc8/200/200',
    consultationFee: 140000,
  },
  {
    id: 9,
    name: 'Dr. Chloe Dubois',
    specialty: 'Indwara z\'abagore (Gynecologist)',
    rating: 4.9,
    reviews: 350,
    imageUrl: 'https://picsum.photos/seed/doc9/200/200',
    consultationFee: 130000,
  },
  {
    id: 10,
    name: 'Dr. Kenji Tanaka',
    specialty: 'Impyiko (Nephrologist)',
    rating: 4.8,
    reviews: 175,
    imageUrl: 'https://picsum.photos/seed/doc10/200/200',
    consultationFee: 155000,
  },
];