
import type { Doctor } from './types';

export const DOCTORS: Doctor[] = [
  {
    id: 1,
    name: 'Dr. Evelyn Reed',
    specialty: 'Umutima (Cardiologist)',
    imageUrl: 'https://picsum.photos/seed/doc1/200/200',
    bio: 'Dr. Reed afite uburambe bw\'imyaka 15 mu kuvura indwara z\'umutima. Yarangije muri Kaminuza y\'u Rwanda kandi azwiho ubuhanga mu kwita ku barwayi.',
    rating: 4.9,
    reviews: 124,
    consultationFee: 25000,
    available: true,
    languages: ['Ikinyarwanda', 'Icyongereza', 'Igifaransa'],
  },
  {
    id: 2,
    name: 'Dr. Samuel Chen',
    specialty: 'Ubuvuzi Rusange',
    imageUrl: 'https://picsum.photos/seed/doc2/200/200',
    bio: 'Dr. Chen ni umuganga w\'ubuvuzi rusange witangira gufasha imiryango. Azwiho kugira urugwiro no gusobanurira abarwayi neza.',
    rating: 4.8,
    reviews: 98,
    consultationFee: 15000,
    available: true,
    languages: ['Ikinyarwanda', 'Icyongereza', 'Igishinwa'],
  },
  {
    id: 3,
    name: 'Dr. Isabella Monroe',
    specialty: 'Uruhu (Dermatologist)',
    imageUrl: 'https://picsum.photos/seed/doc3/200/200',
    bio: 'Dr. Monroe ni inzobere mu ndwara z\'uruhu. Afasha abarwayi bafite ibibazo by\'uruhu, umusatsi, n\'inzara.',
    rating: 4.9,
    reviews: 210,
    consultationFee: 20000,
    available: false,
    languages: ['Icyongereza', 'Igiswahili'],
  },
  {
    id: 4,
    name: 'Dr. Ben Carter',
    specialty: 'Abana (Pediatrician)',
    imageUrl: 'https://picsum.photos/seed/doc4/200/200',
    bio: 'Dr. Carter akunda kwita ku bana kandi afite ubuhanga mu kuvura indwara zibasira abana kuva bakivuka kugeza mu bugimbi.',
    rating: 4.7,
    reviews: 85,
    consultationFee: 18000,
    available: true,
    languages: ['Ikinyarwanda', 'Icyongereza'],
  },
];
